name: Deploy-Auth

on:
    push:
        branches:
            - master
        paths:
            - 'auth/**'

env:
    IMAGE_NAME: auth
    REGISTRY: registry.digitalocean.com/itsadockerhub

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Build container image
              run: cd auth && docker build -t $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) .

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 1200

            - name: Push image to DigitalOcean Container Registry
              run: docker push $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tickets

            - name: Deploy to DigitalOcean Kubernetes
              run: kubectl apply -f $GITHUB_WORKSPACE/infra/k8s/auth-depl.yaml

            - name: Restart deployment
              run: kubectl rollout restart deployment auth-depl
