name: Deploy-auth

on:
    push:
        branches:
            - master
        paths:
            - 'auth/**'

env:
    IMAGE_NAME: auth
    REGISTRY: registry.digitalocean.com/itsadockerhub/tickets

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v2

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Build container image
              run: cd auth && docker build -t $REGISTRY:$IMAGE_NAME .

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 1200

            - name: Push image to DigitalOcean Container Registry
              run: docker push $REGISTRY:$IMAGE_NAME

            - name: Save DigitalOcean kubeconfig with short-lived credentials
              run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 tickets

            - name: Restart deployment
              run: kubectl rollout restart deployment auth-depl
