name: Test-Orders

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Unit tests
              run: cd orders && npm install && npm run test:ci
